###########################################
# training parameters
###########################################
--- !train
is_training: true
batch_size: 2  
num_epochs: 0
shuffle: true
filenames_shuffle_buffer_size: 100
num_parallel_map_calls: 2
num_readers: 32
read_block_length: 32
shuffle_buffer_size: 2048
prefetch_size: 512

###########################################
# model parameters
###########################################
--- !model
input_shape: [360, 360]
output_shape: [90, 90]
num_keypoints: 15

